version: '3'

services:
  db:
    image: mariadb
    volumes:
      - ./sql_init:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
      MYSQL_DATABASE: edufi_marks_xchg
    ports:
      - 9161:3306

  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - db
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
    ports:
      - 9162:80

  redis:
    image: "redis:alpine"
    command: redis-server --requirepass ${REDIS_PASS}
    ports:
      - 9163:6379
    volumes:
      - redis_data:/var/lib/redis

  trades:
    env_file:
      - .env
    image: caengnp/trades
    ports:
      - 9165:9165

  frontend:
    env_file:
      - .env
    image: caengnp/eti2frontend
    ports:
      - 9160:9160

volumes:
  db_data:
  redis_data:
