services:
  db:
    image: mariadb
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS:?database password not set}
      MYSQL_DATABASE: edufi_marks_xchg
    ports:
      - 9161:3306

  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - db
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS:?database password not set}
    ports:
      - 9162:80

  redis:
    image: "redis:alpine"
    command: redis-server --requirepass ${REDIS_PASS:?redis password not set}
    ports:
      - "9163:6379"
    volumes:
      - redis_data:/var/lib/redis

volumes:
  db_data:
  redis_data:
